CREATE TABLE taille (
    id INT AUTO_INCREMENT PRIMARY KEY,
    categorie TEXT,
    nom VARCHAR(100) NOT NULL,
    description TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO taille (categorie, nom, description) VALUES

('Taille', 'Taille standard', 'Taille standard'),
-- 🔹 Tailles standards (universelles)
('Vêtements', 'XS', 'Très petit'),
('Vêtements', 'S', 'Petit'),
('Vêtements', 'M', 'Moyen'),
('Vêtements', 'L', 'Large'),
('Vêtements', 'XL', 'Très large'),
('Vêtements', 'XXL', 'Très très large'),
('Vêtements', 'XXXL', 'Grand gabarit'),
-- 🔹 Tailles numériques (Europe)
('Vêtements', '34', 'Taille EU 34 (XS)'),
('Vêtements', '36', 'Taille EU 36 (S)'),
('Vêtements', '38', 'Taille EU 38 (M)'),
('Vêtements', '40', 'Taille EU 40 (L)'),
('Vêtements', '42', 'Taille EU 42 (XL)'),
('Vêtements', '44', 'Taille EU 44 (XXL)'),
('Vêtements', '46', 'Taille EU 46 (XXXL)'),
-- 🔹 Tailles US / UK (utilisées souvent dans e-commerce international)
('Vêtements', 'US XS', 'Taille US XS'),
('Vêtements', 'US S', 'Taille US S'),
('Vêtements', 'US M', 'Taille US M'),
('Vêtements', 'US L', 'Taille US L'),
('Vêtements', 'US XL', 'Taille US XL'),
('Vêtements', 'UK 8', 'Taille UK 8'),
('Vêtements', 'UK 10', 'Taille UK 10'),
('Vêtements', 'UK 12', 'Taille UK 12'),
('Vêtements', 'UK 14', 'Taille UK 14'),
-- 🔹 Tailles de chaussures (EU)
('Chaussures', '35', 'Pointure EU 35'),
('Chaussures', '36', 'Pointure EU 36'),
('Chaussures', '37', 'Pointure EU 37'),
('Chaussures', '38', 'Pointure EU 38'),
('Chaussures', '39', 'Pointure EU 39'),
('Chaussures', '40', 'Pointure EU 40'),
('Chaussures', '41', 'Pointure EU 41'),
('Chaussures', '42', 'Pointure EU 42'),
('Chaussures', '43', 'Pointure EU 43'),
('Chaussures', '44', 'Pointure EU 44'),
('Chaussures', '45', 'Pointure EU 45'),
('Chaussures', '46', 'Pointure EU 46'),
('Chaussures', '47', 'Pointure EU 47'),
-- 🔹 Tailles de chaussures (US & UK)
('Chaussures', 'US 6', 'Pointure US 6'),
('Chaussures', 'US 7', 'Pointure US 7'),
('Chaussures', 'US 8', 'Pointure US 8'),
('Chaussures', 'US 9', 'Pointure US 9'),
('Chaussures', 'US 10', 'Pointure US 10'),
('Chaussures', 'US 11', 'Pointure US 11'),
('Chaussures', 'UK 5', 'Pointure UK 5'),
('Chaussures', 'UK 6', 'Pointure UK 6'),
('Chaussures', 'UK 7', 'Pointure UK 7'),
('Chaussures', 'UK 8', 'Pointure UK 8'),
-- 🔹 Tailles de sous-vêtements et lingerie
('Sous-vêtements', '85A', 'Taille soutien-gorge'),
('Sous-vêtements', '90B', 'Taille soutien-gorge'),
('Sous-vêtements', '95C', 'Taille soutien-gorge'),
('Sous-vêtements', '100D', 'Taille soutien-gorge'),
('Sous-vêtements', '105E', 'Taille soutien-gorge'),
('Sous-vêtements', 'T1', 'Slip/T-shirt Taille 1'),
('Sous-vêtements', 'T2', 'Slip/T-shirt Taille 2'),
('Sous-vêtements', 'T3', 'Slip/T-shirt Taille 3'),
('Sous-vêtements', 'T4', 'Slip/T-shirt Taille 4'),
-- 🔹 Tailles enfants (en années ou mois)
('Bébé & Enfants', '0-3 mois', 'Bébé 0 à 3 mois'),
('Bébé & Enfants', '3-6 mois', 'Bébé 3 à 6 mois'),
('Bébé & Enfants', '6-9 mois', 'Bébé 6 à 9 mois'),
('Bébé & Enfants', '9-12 mois', 'Bébé 9 à 12 mois'),
('Bébé & Enfants', '12-18 mois', 'Bébé 1 an'),
('Bébé & Enfants', '2 ans', 'Enfant 2 ans'),
('Bébé & Enfants', '3 ans', 'Enfant 3 ans'),
('Bébé & Enfants', '4 ans', 'Enfant 4 ans'),
('Bébé & Enfants', '5 ans', 'Enfant 5 ans'),
('Bébé & Enfants', '6 ans', 'Enfant 6 ans'),
('Bébé & Enfants', '8 ans', 'Enfant 8 ans'),
('Bébé & Enfants', '10 ans', 'Enfant 10 ans'),
('Bébé & Enfants', '12 ans', 'Enfant 12 ans'),
('Bébé & Enfants', '14 ans', 'Adolescent 14 ans'),
('Bébé & Enfants', '16 ans', 'Adolescent 16 ans'),
-- 🔹 Tailles d’articles de sport
('Sport & Loisirs', 'Petit', 'Petit'),
('Sport & Loisirs', 'Moyen', 'Moyen'),
('Sport & Loisirs', 'Large', 'Large'),
('Sport & Loisirs', 'Très large', 'Très large'),
('Sport & Loisirs', 'Très très large', 'Très très large'),
('Sport & Loisirs', 'Taille unique', 'Article ajustable'),

-- 🔹 Tailles accessoires / bagagerie

('Accessoires', 'Petit', 'Format compact'),
('Accessoires', 'Moyen', 'Format moyen'),
('Accessoires', 'Grand', 'Format large'),
('Accessoires', 'XL', 'Très grand format');
